version: '3.9'
services:
  fastapi: 
    container_name: fastapi
    restart: unless-stopped
    env_file: 
      - .env 
    build: 
      context: ./
      dockerfile: Dockerfile 
      labels:
        - fastapi
    command: 
      - /bin/sh 
      - -c 
      - |
        gunicorn main:app \
        --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:5000
    
    ports:
      - 5000:5000